version: '2'
services:
  app:
    build:
      context: ./serene
      dockerfile: docker/app/Dockerfile
    volumes:
      - /srv/docker/app:/var/lib/app
  postgres:
    build:
      context: ./serene
      dockerfile: docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=serene
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
