version: '2'
services:
  ui_build:
    hostname: ui_build
    build:
      context: ./serene
      dockerfile: docker/ui_build/Dockerfile
    ports:
    - 8080:8080
    volumes:
    - ./serene/ui:/ui
  serene:
    depends_on:
    - ui_build
    - mongo
    hostname: serene
    build:
      context: ./serene
      dockerfile: docker/app/Dockerfile
    ports:
    - 3000:3000
    volumes:
    - ./serene/app:/serene
    - ./serene/ui/dist:/ui
    - mongostore:/data/db
    - coderunner:/coderunner
    - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    hostname: mongo
    build:
      context: ./serene
      dockerfile: docker/mongo/Dockerfile
    volumes:
    - mongostore:/data/db
    ports:
    - 27018:27018
  kafka:
    hostname: kafka
    build:
      context: ./serene/docker/kafka-docker
      dockerfile: ./Dockerfile
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: 10.138.0.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka-client:
    hostname: kafka-client
    build:
      context: ./serene
      dockerfile: docker/kafka-client/Dockerfile

volumes:
  coderunner:
    external: true
  mongostore:
    external: true
