version: '2'
services:
  ui_build:
    hostname: ui_build
    build:
      context: ./serene
      dockerfile: docker/ui_build/Dockerfile
    ports:
    - 8080:8080
    volumes:
    - ./serene/ui:/ui
  serene:
    depends_on:
    - ui_build
    - postgres
    hostname: serene
    build:
      context: ./serene
      dockerfile: docker/app/Dockerfile
    ports:
    - 80:5000
    environment:
    - PYTHONPATH=/serene
    - PYTHONUNBUFFERED=0
    volumes:
    - ./serene/ui/dist:/serene/ui
  postgres:
    hostname: postgres
    build:
      context: ./serene
      dockerfile: docker/postgres/Dockerfile
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=serene
    volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
