version: '2'
services:
  ui_build:
    hostname: ui_build
    build:
      context: ./serene
      dockerfile: docker/ui_build/Dockerfile
    ports:
    - 8080:8080
    volumes:
    - ./serene/ui:/ui
  serene:
    depends_on:
    - ui_build
    - mongo
    hostname: serene
    build:
      context: ./serene
      dockerfile: docker/app/Dockerfile
    ports:
    - 3000:3000
    volumes:
    - ./serene/app:/serene
    - ./serene/ui/dist:/ui
    - mongostore:/data/db
  mongo:
    hostname: mongo
    build:
      context: ./serene
      dockerfile: docker/mongo/Dockerfile
    volumes:
    - mongostore:/data/db
    ports:
    - 27018:27018
volumes:
  mongostore:
