services:
  postgres:
    build:
      context: ./serene
      dockerfile: docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=serene
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
version: '2'
