version: '3.0'
services:
  app:
    depends_on:
    - postgres
    hostname: app
    build:
      context: ./serene
      dockerfile: docker/app/Dockerfile
    volumes:
    - /srv/docker/app:/var/lib/app
    ports:
    - 5000:5000
  postgres:
    hostname: postgres
    build:
      context: ./serene
      dockerfile: docker/postgres/Dockerfile
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=serene
    volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
