version: '2'
services:
  ui_build:
    hostname: ui_build
    build:
      context: ./serene
      dockerfile: docker/ui_build/Dockerfile
    volumes:
    - ./serene/ui:/ui
  app:
    depends_on:
    - ui_build
    - postgres
    hostname: app
    build:
      context: ./serene
      dockerfile: docker/app/Dockerfile
    ports:
    - 80:5000
    environment:
    - PYTHONPATH=/srv/serene
  postgres:
    hostname: postgres
    build:
      context: ./serene
      dockerfile: docker/postgres/Dockerfile
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=serene
    volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
